export { default as drop_down_icon } from "./drop-down-icon.svg";
export { default as logo } from "./logo.svg";
export { default as user_icon } from "./user-icon.svg";
export { default as menu_icon } from "./menu.svg";
export { default as search_icon } from "./search_icon.svg"
export { default as drop_down__red_icon } from "./down-arrow.svg"
export { default as drop_up_red_icon } from "./up-arrow.svg"
export { default as close_icon } from "./close.svg";
export { default as location_icon } from "./location.svg";
export { default as enquiry_icon } from "./enquiry_icon.svg";
export { default as details_icon } from "./details_icon.svg";
export { default as bed_icon } from "./bed.svg";
export { default as bath_icon } from "./bath.svg";
export { default as christmas__icon_star } from "./christmas_stars_icon.svg";
export { default as camera_icon } from "./camera_icon.svg";
export { default as no_image_placeholder } from "./no_image_placeholder.svg";
export { default as tick_green_icon } from "./tick_green_icon.svg";
export { default as info_icon } from "./info_icon.svg";
export { default as black_right_down_icon } from "./black_right_down.svg";
export { default as black_down_icon } from "./black_down_icon.svg";
export { default as back_red_icon } from "./back-to.svg";
export { default as save_icon } from "./save_red_icon.svg";
export { default as share_button_icon } from "./share_icon.svg";
export { default as report_icon } from "./report_icon.svg";
export { default as registration_success } from "./registration_success.svg"
export { default as logo_footer_black } from "./PropertysellerBlackLogo.svg";
export { default as youtube_icon_footer } from "./youtube.svg";
export { default as filter_icon } from "./filter.svg";
export { default as instagram_icon } from "./instagram.svg";
export { default as facebook_icon } from "./facebook.svg";
export { default as share_black_icon } from "./share_black.svg";
export { default as wishlist_black_icon } from "./wishlist_icon.svg";
export { default as back_to_black_icon } from "./back_icon.svg";
export { default as home_red_icon } from "./home.svg";
export { default as saved_red_icon } from "./save_red_icon.svg";
export { default as featured_red_icon } from "./featured.svg";
export { default as profile_red_icon } from "./user_rec_icon.svg";
export { default as notification_red_icon } from "./notification.svg";
export { default as top_arrow_icon } from "./top-arrow.svg";
export { default as big_white_logo_icon } from "./PropertysellerBlackLogo.png";
export { default as notes_icon } from "./notes_icon.svg";
export { default as down_icon } from "./down 2.png";
export { default as play_icon } from "./play-button.svg";
export { default as notes_red_edit } from "./notes_red_edit.svg";
export { default as floor_plan } from "./floor_plan.png";
export { default as play_store_footer_icon } from "./google-store.svg";
export { default as app_store_icon } from "./app-store.svg";
export { default as why_dubai_icon } from "./architecture-ancient-monument-world-heritage-day-celebration.webp";
export { default as high_roi_icon } from "./high_roi_icon.svg";
export { default as no_tax } from "./no-tax.svg";
export { default as propertySellerWhiteLogo } from "./PropertysellerWhiteLogo.svg";
export { default as apartment_icon } from "./apartment.svg";
export { default as penthouse_icon } from "./penthouse.svg";
export { default as townhouse_icon } from "./townhouse.svg";
export { default as villa_icon } from "./villa.svg";
export { default as ownership_icon } from "./ownership.svg"
export { default as economy_icon } from "./economy.svg"
export { default as tourism_icon } from "./tourism.svg"
export { default as property_seller_black_new_logo_icon } from "./PropertysellerBlackLogo-new.png"
export { default as world_class_icon } from "./world-class.svg"
export { default as security_icon } from "./security.svg"
export { default as residency_icon } from "./residency.svg"
export { default as property_options_icon } from "./property.svg"
export { default as flexible_icon } from "./flexible.svg"
export { default as mega_projects_icon } from "./mega.svg"
export { default as explore_icon } from "./explore.svg"
export { default as propertySellerWhiteLogo_icon } from "./PropertysellerWhiteLogo.svg"
export {default as logoWebP} from "./logo.webp"
export {default as mobileAppIcon} from "./mobile-menu-app-icon.png"